set(CTOOLS_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ctools/include)
set(CTOOLS_LIBRARIES ctools)

set(USE_GL_VERSION_CHECKER OFF CACHE BOOL "" FORCE)
set(USE_CONFIG_SYSTEM ON CACHE BOOL "" FORCE)
set(USE_GLFW_CLIPBOARD ON CACHE BOOL "" FORCE)
include_directories(
	${GLFW_INCLUDE_DIR}
)

if(USE_SHARED_LIBS)
	set(USE_SHARED_LIB_CTOOLS ON CACHE BOOL "" FORCE)
else()
	set(USE_SHARED_LIB_CTOOLS OFF CACHE BOOL "" FORCE)
endif()

add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/ctools)

if(USE_SHARED_LIBS)
	set(USE_SHARED_LIB_CTOOLS ON CACHE BOOL "" FORCE)
	set_target_properties(ctools PROPERTIES FOLDER 3rdparty/Shared/aiekick)
else()
	set(USE_SHARED_LIB_CTOOLS OFF CACHE BOOL "" FORCE)
	set_target_properties(ctools PROPERTIES FOLDER 3rdparty/Static/aiekick)
endif()

set_target_properties(ctools PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${FINAL_BIN_DIR}")
set_target_properties(ctools PROPERTIES RUNTIME_OUTPUT_DIRECTORY_DEBUG "${FINAL_BIN_DIR}")
set_target_properties(ctools PROPERTIES RUNTIME_OUTPUT_DIRECTORY_RELEASE "${FINAL_BIN_DIR}")
set_target_properties(ctools PROPERTIES LIBRARY_OUTPUT_DIRECTORY "${FINAL_BIN_DIR}")
set_target_properties(ctools PROPERTIES LIBRARY_OUTPUT_DIRECTORY_DEBUG "${FINAL_BIN_DIR}")
set_target_properties(ctools PROPERTIES LIBRARY_OUTPUT_DIRECTORY_RELEASE "${FINAL_BIN_DIR}")
